### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by allemas** [TagCommander/react-tag-commander#18]
Hello,
I use react-tag-commander in a react(v.17) project, everything seems to work fine but when I run the tests I get an error : 

```
\node_modules\react-tag-commander\src\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React, { Component } from 'react';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      13 |
      14 | import { drupalLinksApi, DrupalMenu } from '../../modules/DrupalModule/utils/drupal-menu';
    > 15 | import TC_Wrapper, { withTracker } from "react-tag-commander";
         | ^
      16 |
      17 |
      18 |

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (src/containers/App/App.jsx:15:1)
```
Maybe I'm doing something wrong but when I search on the web I have the feeling that I should use the resources available in the Dist folder rather than doing an ES6 import.

Your documentation shows that both are possible so I'll drop by here to see if I have any help.

**Comment by allemas** [comment]
Problem solved. 
An import of React has leaked in test files...

**Comment by Dupflo** [comment]
Same error, how did you fix that ?
